In [1]:
import numpy as np

BASIC ARRAY CREATION


In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3.21]
a

[1, 2, 3.21]

In [4]:
np.array(a)

array([1.  , 2.  , 3.21])

In [5]:
l  = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GENERATION FUNCTION 

In [7]:
# same as range() 
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [8]:
z = np.zeros((4,8))
z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
o = np.ones((6,6))
o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
lin = np.linspace(0,1,100)
lin

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

RANDOM GENERATION FUNCTION

In [11]:
np.random.rand(10)
# normalization = values from 0 to 1

array([0.3249739 , 0.91400076, 0.15326834, 0.50922323, 0.53350355,
       0.64310104, 0.6742673 , 0.46326799, 0.60014975, 0.58087196])

In [12]:
# standardization = values from -3 to 3
np.random.randn(10)

array([ 0.31052646,  0.61020052, -0.13441452,  0.69077712, -2.21115001,
        1.04527232, -0.31942011,  0.96944419, -0.01697597, -0.34737826])

In [13]:
np.random.randint(10,20,10)

array([13, 13, 14, 19, 10, 18, 16, 19, 13, 11], dtype=int32)

ARRAY ATTRIBUTES  

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
# return shape of array 
arr.shape

(3, 3)

In [16]:
# return size of array 
arr.size

9

In [17]:
# return datatype of array 
arr.dtype

dtype('int64')

ARRAY METHODS

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.min()

np.int64(1)

In [20]:

arr.max()

np.int64(9)

In [21]:
# sum of all elements are present in array
arr.sum()

np.int64(45)

In [22]:
# summation of columns 
np.sum(arr,axis = 0)


array([12, 15, 18])

In [23]:
# summation of rows 
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [24]:
# mean of array
arr.mean()

np.float64(5.0)

In [25]:
# standard deviation 
arr.std()

np.float64(2.581988897471611)

In [26]:
# returns the index of maximum element that present on array
arr.argmax()

np.int64(8)

In [27]:
# returns the index of minimum element that present on array
arr.argmin()

np.int64(0)

Reshaping and Resizing 

In [28]:
arr2 = np.arange(1,31)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [29]:
# Reshaping
arr2.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [30]:
# Resizing
arr2 = arr2.reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

 ARRAY INDEXING AND SLICING


Indexing and Slicing Of Vectors

In [31]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
# Indexing same as python
arr_index = arr[9]
arr_index

np.int64(20)

In [33]:
# Slicing same as python
arr_slice = arr[1:8]
arr_slice

array([12, 13, 14, 15, 16, 17, 18])

In [34]:
arr[::2]

array([11, 13, 15, 17, 19])

In [35]:
arr_reverce = arr[::-1]
arr_reverce

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])


Indexing and Slicing Of Matrix

In [36]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
#  Slicing row
arr[3]

array([16, 17, 18, 19, 20])

In [38]:
# 1st way
 
arr[0][0]
# 1st [] = represent rows 
# 2nd [] = represent columns

np.int64(1)

In [39]:
# 2nd way
 
arr[5,4]
# 1st element  = represent rows 
# 2nd element  = represent columns

np.int64(30)

In [40]:
#  for 2, 3
#      7, 8
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [41]:
slice2 = arr[3:,3:]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [42]:
# Slicing Column
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [43]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [45]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

ARRAY OPERATIONS

Arithmetic Operations 


In [46]:
# Size must be same of both arrays
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [47]:
add = a1 + a2
add

array([ 7,  9, 11, 13, 15])

In [48]:
sub = a1 - a2
sub

array([-5, -5, -5, -5, -5])

In [49]:
mul = a1 * a2
mul

array([ 6, 14, 24, 36, 50])

In [50]:
expo = a1 ** a2
expo

array([      1,     128,    6561,  262144, 9765625])

In [51]:
div = a1 / a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [52]:
f_div = a1 // a2
f_div

array([0, 0, 0, 0, 0])

Broadcasting

In [53]:
l = [10,20,30,40,50]
arr = np.array(l)

In [54]:
arr + 10

array([20, 30, 40, 50, 60])

In [55]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [57]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow Copy

In [58]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
# Deep copy Eg.
a_copy = a.copy()
a_copy[0] = 99
print(a)
print(a_copy)

[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]


In [61]:
# Shallow copy Eg.
b = a
b[0] = 99
print(a)
print(b)

[99  2  3  4  5  6  7  8  9 10]
[99  2  3  4  5  6  7  8  9 10]


Matrix Operatios

In [62]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [63]:
a

array([[1, 2],
       [3, 4]])

In [64]:
b

array([[5, 6],
       [7, 8]])

In [65]:
# Dot product (multiplication)
a @ b  # 1st way
np.dot(a,b)  # 2nd way

array([[19, 22],
       [43, 50]])

In [66]:
#  Transpose 
a.T

array([[1, 3],
       [2, 4]])

In [67]:
b.T

array([[5, 7],
       [6, 8]])

Advance Array Manipulation 

1. Stacking Array


In [68]:
# must be performed on Vectors
# can't be performed on matrix
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [69]:
#  Type 1:- Vertical Stack
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
# Type 2:- Horizontal Stack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
# Type 3:- Column Stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

2. Splitting Array

In [72]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
# Type 1:- Vertical Split 
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [74]:
#  Type 2:- Horizontal Split
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

EXERCISE


In [116]:
# Columns: [Age, Math Marks, Science MArks]

data = np.array([
    [18,85,78],  # Student 1 
    [19,92,88],  # Student 2
    [17,76,95],  # Student 3
    [18,65,70],  # Student 4
    [20,90,85]   # Student 5
])

In [117]:
#  Get the shape of the Matrix
data.shape

(5, 3)

In [118]:
# Find the average age of students
avg = np.mean(data[:,0])
print("Average Age of Students: ",avg)

Average Age of Students:  18.4


In [119]:
# Extract Math marks of all Students
math_marks = data[:,1]
print("Math Marks:" ,math_marks)

Math Marks: [85 92 76 65 90]


In [120]:
#  Find the highest Science mark
sci_hmark = np.max(data[:,2])
print("Highest Science Mrak: ",sci_hmark)


Highest Science Mrak:  95


In [121]:
# Get details of Student who scored more than 90 in math
data[math_marks > 90]

array([[19, 92, 88]])

In [122]:
# Increase Math marks of all students by 5
print("Math Marks Increades by 5: ")
data[:,1] +=5
data

Math Marks Increades by 5: 


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [123]:
# Find how many students younger than 18
len(data[data[:,0] < 19])

3

In [124]:
# Calculate the average marks in each subject (column-wise mean)
total = np.mean(data[:,1:], axis=0)
total

array([86.6, 83.2])

In [125]:
# Get data of students who scored at least 80 in both subjects
print("Students whos scored at least 80 in both Subjects:")
print(data[(data[:,1] >= 80) & (data[:,2] >= 80) ])

Students whos scored at least 80 in both Subjects:
[[19 97 88]
 [17 81 95]
 [20 95 85]]


In [126]:
# Replace all Science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])